// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWw2aVsgkhsIiJDZHBCC2LrpSGawQkxds',
    appId: '1:1097618173139:web:9f31f18c2597774585b826',
    messagingSenderId: '1097618173139',
    projectId: 'ecommerceapp-e912f',
    authDomain: 'ecommerceapp-e912f.firebaseapp.com',
    storageBucket: 'ecommerceapp-e912f.firebasestorage.app',
    measurementId: 'G-9W52YM502B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXk5U9AHMAbhR0GyNxNbpDSkdFGGIgVs',
    appId: '1:1097618173139:android:fe970ae1a314f12285b826',
    messagingSenderId: '1097618173139',
    projectId: 'ecommerceapp-e912f',
    storageBucket: 'ecommerceapp-e912f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkWRb5KwxHFh6P8Ar2xFlmu-fF5dKy5Tg',
    appId: '1:1097618173139:ios:72dc060461c8c10c85b826',
    messagingSenderId: '1097618173139',
    projectId: 'ecommerceapp-e912f',
    storageBucket: 'ecommerceapp-e912f.firebasestorage.app',
    androidClientId: '1097618173139-giovk6ef82da005orks843j7kuhdn73e.apps.googleusercontent.com',
    iosClientId: '1097618173139-2au7t8kkuaqla5rar4kmgeblvvc9af0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}